export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const SET_SELECTED_DIRECTION = 'SET_SELECTED_DIRECTION';
export const SET_SELECTED_TYPE = 'SET_SELECTED_TYPE';
export const SET_CURRENT_SEMESTER = 'SET_CURRENT_SEMESTER';
export const SET_COLUMNS = 'SET_COLUMNS';
